### ISSUE TITLE
The field annotation of agentSpec should be changed to annotations

### ISSUE THREAD

**Issue by ty-dc** [kdoctor-io/kdoctor#514]
**Describe the version**

**Describe the bug**
```
cat <<EOF | kubectl apply -f -
apiVersion: kdoctor.io/v1beta1
kind: NetReach
metadata:
  name: task
spec:
  expect:
    meanAccessDelayInMs: 1500
    successRate: 1
  request:
    durationInSecond: 10
    perRequestTimeoutInMS: 1000
    qps: 10
  schedule:
    roundNumber: 90000
    roundTimeoutMinute: 1
    schedule: 1 1
  target:
    clusterIP: true
    endpoint: true
    ingress: true
    ipv4: true
    ipv6: true
    loadBalancer: false
    multusInterface: false
    nodePort: true
  agentSpec:
    annotation:
      v1.multus-cni.io/default-network: kube-system/eth1
      k8s.v1.cni.cncf.io/networks: kube-system/eth2
    hostNetwork: false
EOF
```

**Hwo To Reproduce**
Steps to reproduce the issue:

**Expected behavior**

**Screenshots and log**
If applicable, add screenshots and log to help explain your problem.

**Additional context**
